import { NextResponse } from "next/server";
import { db, Timestamp } from "@/lib/firebaseAdmin";
import { verifyRequestRole } from "@/lib/server/verify-role";

const ukviModules = [
  {
    id: "module_1",
    order: 1,
    title: "Fundamentals of University & UKVI Credibility",
    description: "Understand the genuine student rule, ECO roles, and interview purpose.",
    passScore: 80,
    studyNotes: `### 1. Purpose of the Credibility Interview\n- **Genuine Student Rule:** UKVI verifies your primary purpose is academic study, not illegal work.\n- **ECO Role:** Assesses English proficiency, genuine academic intent, and financials.\n- **Pre-CAS Interviews:** Universities conduct these to protect their Sponsor License.\n\n### 2. Key Assessment Indicators\n- **Academic Fit:** Why this degree is the logical next step.\n- **Language Proficiency:** Must converse fluently without scripts or interpreters.\n- **Relevance of Choice:** Why the UK over your home country.`,
    questions: [
      { id: "m1_q1", questionText: "What is the primary objective of a UKVI Credibility Interview?", options: [{ id: "m1_q1_o1", text: "To test fitness levels", isCorrect: false }, { id: "m1_q1_o2", text: "To confirm the applicant is a genuine student", isCorrect: true }, { id: "m1_q1_o3", text: "To qualify for permanent residency", isCorrect: false }] },
      { id: "m1_q2", questionText: "Who conducts the Pre-CAS interview?", options: [{ id: "m1_q2_o1", text: "Home Office", isCorrect: false }, { id: "m1_q2_o2", text: "University compliance team", isCorrect: true }, { id: "m1_q2_o3", text: "British High Commissioner", isCorrect: false }] },
      { id: "m1_q3", questionText: "If an applicant uses an interpreter during a UKVI credibility interview, what is the likely outcome?", options: [{ id: "m1_q3_o1", text: "Bonus points", isCorrect: false }, { id: "m1_q3_o2", text: "Visa refusal due to lack of English competence", isCorrect: true }, { id: "m1_q3_o3", text: "Automatic approval", isCorrect: false }] },
      { id: "m1_q4", questionText: "What does 'GTE' or 'Genuine Student' evaluation mean?", options: [{ id: "m1_q4_o1", text: "Evaluating if the main purpose of travel is quality education", isCorrect: true }, { id: "m1_q4_o2", text: "Checking for dual citizenship", isCorrect: false }, { id: "m1_q4_o3", text: "Testing sports knowledge", isCorrect: false }] },
      { id: "m1_q5", questionText: "What is the standard duration allowed to answer questions?", options: [{ id: "m1_q5_o1", text: "One-word answers exclusively", isCorrect: false }, { id: "m1_q5_o2", text: "Direct, clear, and comprehensive responses without ramble", isCorrect: true }, { id: "m1_q5_o3", text: "Reading 5-minute pre-written speeches", isCorrect: false }] }
    ]
  },
  {
    id: "module_2",
    order: 2,
    title: "CAS & Financial Compliance",
    description: "Master the 28-day rule, maintenance funds, and acceptable sponsors.",
    passScore: 80,
    studyNotes: `### 1. Understanding the CAS\n- **Definition:** 14-character reference number generated by the university.\n- **Validity:** Valid for 6 months, used once.\n\n### 2. Financial Requirements\n- **28-Day Rule:** Total required money must remain in the bank for 28 consecutive days without falling below the minimum.\n- **31-Day Rule:** The closing date of the statement must be within 31 days of visa submission.\n\n### 3. Acceptable Sources\n- Personal accounts (student or biological parents).\n- Official government sponsorship or approved educational loans.\n- *Unacceptable:* Company accounts, uncle/friends, real estate, credit cards.`,
    questions: [
      { id: "m2_q1", questionText: "What does the acronym CAS stand for?", options: [{ id: "m2_q1_o1", text: "Certificate of Academic Status", isCorrect: false }, { id: "m2_q1_o2", text: "Confirmation of Acceptance for Studies", isCorrect: true }, { id: "m2_q1_o3", text: "Certified Admission and Sponsorship", isCorrect: false }] },
      { id: "m2_q2", questionText: "Under UKVI rules, what is the continuous holding period required for liquid funds?", options: [{ id: "m2_q2_o1", text: "14 consecutive days", isCorrect: false }, { id: "m2_q2_o2", text: "28 consecutive days", isCorrect: true }, { id: "m2_q2_o3", text: "90 consecutive days", isCorrect: false }] },
      { id: "m2_q3", questionText: "Whose bank account can be used for a student visa financial evidence without third-party issues?", options: [{ id: "m2_q3_o1", text: "The applicant or biological parents/legal guardians", isCorrect: true }, { id: "m2_q3_o2", text: "Uncle or aunt", isCorrect: false }, { id: "m2_q3_o3", text: "Best friend", isCorrect: false }] },
      { id: "m2_q4", questionText: "What happens if an account balance falls £1 below the required amount on day 20 of the 28-day cycle?", options: [{ id: "m2_q4_o1", text: "Bank tops it up automatically", isCorrect: false }, { id: "m2_q4_o2", text: "The 28-day timer resets, and the financial test is failed", isCorrect: true }, { id: "m2_q4_o3", text: "UKVI approves it with a minor deduction", isCorrect: false }] },
      { id: "m2_q5", questionText: "How many months of living expenses must a student show if their course lasts 12 months?", options: [{ id: "m2_q5_o1", text: "6 months", isCorrect: false }, { id: "m2_q5_o2", text: "9 months (maximum required duration)", isCorrect: true }, { id: "m2_q5_o3", text: "12 months", isCorrect: false }] }
    ]
  },
  {
    id: "module_3",
    order: 3,
    title: "Academic, University & Course Knowledge",
    description: "Learn how to articulate course structures, RQF levels, and academic logic.",
    passScore: 80,
    studyNotes: `### 1. Course Knowledge\n- Must articulate specific core and elective modules by exact title.\n- Know assessment methods (exams, coursework, dissertation).\n- Standard Master's: 180 credits. Bachelor's: 360 credits.\n\n### 2. University Selection\n- Why this city? Know specific labs, libraries, or industry links.\n- Compare with at least 2 other UK universities (tuition, rankings, modules).\n\n### 3. Academic Logic\n- Explain how this degree builds on previous studies.\n- Justify study gaps with professional work or certifications.`,
    questions: [
      { id: "m3_q1", questionText: "When asked 'Why did you choose this course?', what is the most effective answer?", options: [{ id: "m3_q1_o1", text: "It was the cheapest course", isCorrect: false }, { id: "m3_q1_o2", text: "Specific details on module content and how it aligns with career goals", isCorrect: true }, { id: "m3_q1_o3", text: "My parents chose it", isCorrect: false }] },
      { id: "m3_q2", questionText: "How many total credits does a standard 1-year UK Master's degree comprise?", options: [{ id: "m3_q2_o1", text: "120 credits", isCorrect: false }, { id: "m3_q2_o2", text: "180 credits", isCorrect: true }, { id: "m3_q2_o3", text: "360 credits", isCorrect: false }] },
      { id: "m3_q3", questionText: "What is an RQF level 7 qualification equivalent to?", options: [{ id: "m3_q3_o1", text: "Bachelor's Degree", isCorrect: false }, { id: "m3_q3_o2", text: "Master's Degree", isCorrect: true }, { id: "m3_q3_o3", text: "PhD", isCorrect: false }] },
      { id: "m3_q4", questionText: "What does the term 'Dissertation' mean in a UK Master's program?", options: [{ id: "m3_q4_o1", text: "An oral speech given on day one", isCorrect: false }, { id: "m3_q4_o2", text: "An independent research project/thesis completed towards the end", isCorrect: true }, { id: "m3_q4_o3", text: "A preliminary English test", isCorrect: false }] },
      { id: "m3_q5", questionText: "What is the difference between a core module and an elective module?", options: [{ id: "m3_q5_o1", text: "Core is compulsory; elective is optional based on interest", isCorrect: true }, { id: "m3_q5_o2", text: "Core is for international students; elective for UK students", isCorrect: false }, { id: "m3_q5_o3", text: "Core has no exams", isCorrect: false }] }
    ]
  },
  {
    id: "module_4",
    order: 4,
    title: "Career Progression & Return Intentions",
    description: "Demonstrate ROI, home country ties, and avoid immigration red flags.",
    passScore: 80,
    studyNotes: `### 1. Career Strategy\n- State specific target job titles and employers back home.\n- Demonstrate financial ROI (Return on Investment).\n\n### 2. Ties to Home Country\n- Establish intent to return: job offers, family business, assets.\n- **Crucial Rule:** NEVER state an intention to overstay or remain unlawfully.\n\n### 3. Financial Justification\n- Know your sponsor's occupation and annual income.\n- **Work Restrictions:** Student visa work (20hrs/week) is for pocket money, NOT to pay tuition.`,
    questions: [
      { id: "m4_q1", questionText: "What is the maximum allowed work hour limit for a full-time Student Visa holder during term time?", options: [{ id: "m4_q1_o1", text: "10 hours per week", isCorrect: false }, { id: "m4_q1_o2", text: "20 hours per week", isCorrect: true }, { id: "m4_q1_o3", text: "Unlimited hours", isCorrect: false }] },
      { id: "m4_q2", questionText: "Can an international student rely on part-time work earnings to pay tuition fees?", options: [{ id: "m4_q2_o1", text: "Yes, that is expected", isCorrect: false }, { id: "m4_q2_o2", text: "No, UKVI strictly mandates full funds prior to travel", isCorrect: true }, { id: "m4_q2_o3", text: "Yes, if they work 3 jobs", isCorrect: false }] },
      { id: "m4_q3", questionText: "If asked 'Why won't you stay in the UK long-term?', an effective answer emphasizes:", options: [{ id: "m4_q3_o1", text: "Strong personal, family, and lucrative career ties in the home country", isCorrect: true }, { id: "m4_q3_o2", text: "Claiming the UK is a bad place", isCorrect: false }, { id: "m4_q3_o3", text: "Stating jobs do not exist in the UK", isCorrect: false }] },
      { id: "m4_q4", questionText: "What does 'IHS' stand for?", options: [{ id: "m4_q4_o1", text: "International Health Service", isCorrect: false }, { id: "m4_q4_o2", text: "Immigration Health Surcharge", isCorrect: true }, { id: "m4_q4_o3", text: "Internal Housing Scheme", isCorrect: false }] },
      { id: "m4_q5", questionText: "What is a 'Graduate Route' visa?", options: [{ id: "m4_q5_o1", text: "An automatic grant of citizenship", isCorrect: false }, { id: "m4_q5_o2", text: "An optional 2-year post-study work visa to gain experience before returning", isCorrect: true }, { id: "m4_q5_o3", text: "A mandatory requirement", isCorrect: false }] }
    ]
  },
  {
    id: "module_5",
    order: 5,
    title: "Interview Delivery & Behavioral Excellence",
    description: "Master body language, avoid scripted answers, and handle technical glitches.",
    passScore: 80,
    studyNotes: `### 1. Primary Failure Reasons\n- **Coached Answers:** Reciting essays instead of answering the specific question.\n- **Inconsistencies:** Discrepancies between spoken answers and documents.\n- **Poor English:** Reliance on pauses or inability to comprehend questions.\n\n### 2. Professional Conduct\n- Join 10-15 mins early in a quiet, well-lit room.\n- Maintain eye contact with the camera.\n- Listen completely to the question before answering.\n\n### 3. Handling Glitches\n- Immediately inform the interviewer if audio/video drops. Do not guess.\n- **Prohibited:** Looking off-screen at notes or smartphones.`,
    questions: [
      { id: "m5_q1", questionText: "What is the single biggest technical mistake an applicant can make during a video interview?", options: [{ id: "m5_q1_o1", text: "Wearing a dark suit", isCorrect: false }, { id: "m5_q1_o2", text: "Reading answers off hidden notes or screens off-camera", isCorrect: true }, { id: "m5_q1_o3", text: "Drinking water", isCorrect: false }] },
      { id: "m5_q2", questionText: "What should an applicant do if the interviewer's audio freezes?", options: [{ id: "m5_q2_o1", text: "Make up an answer", isCorrect: false }, { id: "m5_q2_o2", text: "Politely state the audio froze and ask to repeat", isCorrect: true }, { id: "m5_q2_o3", text: "End the call immediately", isCorrect: false }] },
      { id: "m5_q3", questionText: "Why do interviewers dislike 'coached' or 'scripted' answers?", options: [{ id: "m5_q3_o1", text: "They sound unnatural and obscure genuine student intent", isCorrect: true }, { id: "m5_q3_o2", text: "They take too short to recite", isCorrect: false }, { id: "m5_q3_o3", text: "Interviewers prefer poetry", isCorrect: false }] },
      { id: "m5_q4", questionText: "What is the impression given when a candidate repeatedly looks to the side before answering?", options: [{ id: "m5_q4_o1", text: "That they are thinking deeply", isCorrect: false }, { id: "m5_q4_o2", text: "That someone in the room is giving them answers", isCorrect: true }, { id: "m5_q4_o3", text: "That they are checking the time", isCorrect: false }] },
      { id: "m5_q5", questionText: "If the ECO asks a simple 'Yes/No' question, what is the best approach?", options: [{ id: "m5_q5_o1", text: "Answer Yes/No and provide a brief, relevant explanation", isCorrect: true }, { id: "m5_q5_o2", text: "Speak for 15 minutes continuously", isCorrect: false }, { id: "m5_q5_o3", text: "Ignore the question", isCorrect: false }] }
    ]
  }
];

export async function POST(request: Request) {
  const authResult = await verifyRequestRole(request, ["Super Admin", "Admin"]);
  if (authResult.error) return authResult.error;

  try {
    const batch = db.batch();
    const modulesRef = db.collection("learning_modules");

    for (const mod of ukviModules) {
      const docRef = modulesRef.doc(mod.id);
      batch.set(docRef, {
        ...mod,
        createdBy: authResult.caller.uid,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      });
    }

    await batch.commit();

    return NextResponse.json({
      success: true,
      message: `${ukviModules.length} UKVI modules seeded successfully.`,
    });
  } catch (e: unknown) {
    console.error("Module seeding error:", e);
    const message = e instanceof Error ? e.message : "Failed to seed modules";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
