import { TestQuestionSet } from "@/types/academy";

/**
 * Hardcoded Curriculum for Core UKVI Modules (1-5)
 * Adheres strictly to the Academy data schema.
 */
export const CORE_UKVI_MODULES: Partial<TestQuestionSet>[] = [
  {
    id: "core_ukvi_m1",
    title: "Module 1: Introduction to UKVI Compliance",
    timePerQuestionSeconds: 10,
    isRandomized: true,
    isArchived: false,
    isDefault: true,
    category: "core",
    orderIndex: 1,
    learningContent: `
      <div class="space-y-4">
        <h3 class="text-xl font-black text-blue-600 uppercase">Welcome to UKVI Compliance Foundations</h3>
        <p class="text-sm leading-relaxed">Before you enter the test arena, understand that the <strong>UK Visas and Immigration (UKVI)</strong> division of the Home Office evaluates international students based on their <strong>intent</strong> and <strong>credibility</strong>.</p>
        <div class="p-5 bg-blue-50 dark:bg-blue-900/20 rounded-2xl border border-blue-100 dark:border-blue-800">
           <h4 class="text-xs font-black uppercase mb-2">Key Compliance Pillars:</h4>
           <ul class="list-disc list-inside text-xs space-y-1 font-bold">
              <li>Genuine Student Test: Proving your primary reason for travel is education.</li>
              <li>Immigration History: Full disclosure of previous visa refusals globally.</li>
              <li>Institutional Research: Deep knowledge of your chosen university and course.</li>
           </ul>
        </div>
        <p class="text-[10px] font-black uppercase text-gray-400">Mission Parameters: 10 Randomized Questions • 10 Seconds Per Question • 80% Required to Pass.</p>
      </div>
    `,
    questions: [
      { id: "m1_q1", prompt: "What does UKVI stand for?", options: [{ id: "o1", text: "UK Visas and Immigration" }, { id: "o2", text: "UK Visa Institute" }, { id: "o3", text: "United Kingdom Visa Int." }, { id: "o4", text: "University Knowledge & Visa Information" }], correctOptionId: "o1", explanation: "UKVI is the division of the Home Office responsible for the UK's visa system." },
      { id: "m1_q2", prompt: "Which government department is responsible for UKVI?", options: [{ id: "o1", text: "Department of Education" }, { id: "o2", text: "The Home Office" }, { id: "o3", text: "Foreign & Commonwealth Office" }, { id: "o4", text: "Department for Business" }], correctOptionId: "o2", explanation: "UKVI is a division of the Home Office." },
      { id: "m1_q3", prompt: "What is the primary purpose of the 'Credibility Interview'?", options: [{ id: "o1", text: "To check your English speaking speed" }, { id: "o2", text: "To verify if you are a genuine student" }, { id: "o3", text: "To take your fingerprints" }, { id: "o4", text: "To discuss UK tourist attractions" }], correctOptionId: "o2", explanation: "The interview ensures you genuinely intend to study and have researched your options." },
      { id: "m1_q4", prompt: "Which of these is a valid reason for a student visa refusal?", options: [{ id: "o1", text: "Having too many qualifications" }, { id: "o2", text: "Insufficient financial evidence" }, { id: "o3", text: "Applying 3 months early" }, { id: "o4", text: "Studying in a cold city" }], correctOptionId: "o2", explanation: "Financial non-compliance is a major reason for refusal." },
      { id: "m1_q5", prompt: "True or False: You can work 40 hours per week during term time.", options: [{ id: "o1", text: "True" }, { id: "o2", text: "False" }], correctOptionId: "o2", explanation: "Term-time work is usually restricted to 20 hours per week for degree-level students." },
      { id: "m1_q6", prompt: "What is the CAS in the student visa process?", options: [{ id: "o1", text: "Course Admission System" }, { id: "o2", text: "Confirmation of Acceptance for Studies" }, { id: "o3", text: "Certified Academic Statement" }, { id: "o4", text: "Customs and Security" }], correctOptionId: "o2" },
      { id: "m1_q7", prompt: "How long is a CAS valid for?", options: [{ id: "o1", text: "12 months" }, { id: "o2", text: "6 months" }, { id: "o3", text: "3 months" }, { id: "o4", text: "1 month" }], correctOptionId: "o2" },
      { id: "m1_q8", prompt: "What is the IHS?", options: [{ id: "o1", text: "International Health Surcharge" }, { id: "o2", text: "Immigration Home Service" }, { id: "o3", text: "Internal Housing System" }, { id: "o4", text: "Institute for Higher Studies" }], correctOptionId: "o1" },
      { id: "m1_q9", prompt: "Who must pay the International Health Surcharge?", options: [{ id: "o1", text: "Only students from the USA" }, { id: "o2", text: "Most visa applicants staying over 6 months" }, { id: "o3", text: "Only students with pre-existing conditions" }, { id: "o4", text: "No one, it is optional" }], correctOptionId: "o2" },
      { id: "m1_q10", prompt: "What is the RQF level for a Bachelor's degree?", options: [{ id: "o1", text: "Level 4" }, { id: "o2", text: "Level 6" }, { id: "o3", text: "Level 7" }, { id: "o4", text: "Level 8" }], correctOptionId: "o2" },
      { id: "m1_q11", prompt: "What is the RQF level for a Master's degree?", options: [{ id: "o1", text: "Level 5" }, { id: "o2", text: "Level 6" }, { id: "o3", text: "Level 7" }, { id: "o4", text: "Level 8" }], correctOptionId: "o3" },
      { id: "m1_q12", prompt: "Which document confirms your course details for the visa?", options: [{ id: "o1", text: "Birth Certificate" }, { id: "o2", text: "CAS" }, { id: "o3", text: "High School Diploma" }, { id: "o4", text: "Bank Statement" }], correctOptionId: "o2" },
      { id: "m1_q13", prompt: "How many months of maintenance funds are required for London?", options: [{ id: "o1", text: "6 months" }, { id: "o2", text: "9 months" }, { id: "o3", text: "12 months" }, { id: "o4", text: "The whole course" }], correctOptionId: "o2" },
      { id: "m1_q14", prompt: "What is the '28-day rule'?", options: [{ id: "o1", text: "Funds must be held for 28 consecutive days" }, { id: "o2", text: "You must apply 28 days after getting CAS" }, { id: "o3", text: "You must arrive 28 days before course starts" }, { id: "o4", text: "Refusal must be appealed in 28 days" }], correctOptionId: "o1" },
      { id: "m1_q15", prompt: "Where do you find the most accurate visa guidance?", options: [{ id: "o1", text: "Social Media" }, { id: "o2", text: "GOV.UK" }, { id: "o3", text: "Unverified blogs" }, { id: "o4", text: "Travel agents only" }], correctOptionId: "o2" },
      { id: "m1_q16", prompt: "What is a BRP?", options: [{ id: "o1", text: "Biometric Residence Permit" }, { id: "o2", text: "Basic Registration Paper" }, { id: "o3", text: "British Residency Pass" }, { id: "o4", text: "Boarding and Road Permit" }], correctOptionId: "o1" },
      { id: "m1_q17", prompt: "Do you need a visa to study in the UK if you are a non-EEA national?", options: [{ id: "o1", text: "No" }, { id: "o2", text: "Yes" }], correctOptionId: "o2" },
      { id: "m1_q18", prompt: "What is the maximum study limit for degree level study?", options: [{ id: "o1", text: "2 years" }, { id: "o2", text: "5 years (with exceptions)" }, { id: "o3", text: "Unlimited" }, { id: "o4", text: "10 years" }], correctOptionId: "o2" },
      { id: "m1_q19", prompt: "Which of these is NOT a student visa requirement?", options: [{ id: "o1", text: "Valid CAS" }, { id: "o2", text: "Financial proof" }, { id: "o3", text: "A job offer in the UK" }, { id: "o4", text: "English language proficiency" }], correctOptionId: "o3" },
      { id: "m1_q20", prompt: "What is SELT?", options: [{ id: "o1", text: "Secure English Language Test" }, { id: "o2", text: "Student Entry Level Training" }, { id: "o3", text: "System for Electronic Labour Tracking" }, { id: "o4", text: "Standard Entry Log Template" }], correctOptionId: "o1" },
      { id: "m1_q21", prompt: "Which body regulates UK universities?", options: [{ id: "o1", text: "Office for Students (OfS)" }, { id: "o2", text: "The Police" }, { id: "o3", text: "The NHS" }, { id: "o4", text: "BBC" }], correctOptionId: "o1" },
      { id: "m1_q22", prompt: "What is the TB test requirement for certain countries?", options: [{ id: "o1", text: "Tuberculosis screening" }, { id: "o2", text: "Technical Background check" }, { id: "o3", text: "Travel Booking verification" }, { id: "o4", text: "Total Budget assessment" }], correctOptionId: "o1" },
      { id: "m1_q23", prompt: "What happens if you use fake documents?", options: [{ id: "o1", text: "You get a warning" }, { id: "o2", text: "You are banned for up to 10 years" }, { id: "o3", text: "You pay a small fine" }, { id: "o4", text: "Nothing" }], correctOptionId: "o2" },
      { id: "m1_q24", prompt: "Can you switch your visa from within the UK?", options: [{ id: "o1", text: "Always" }, { id: "o2", text: "Never" }, { id: "o3", text: "Only under specific conditions" }, { id: "o4", text: "Only as a tourist" }], correctOptionId: "o3" },
      { id: "m1_q25", prompt: "What is the ATAS requirement?", options: [{ id: "o1", text: "Security clearance for certain sensitive courses" }, { id: "o2", text: "Academic Transcript Authentication Service" }, { id: "o3", text: "Advanced Travel Authorization System" }, { id: "o4", text: "Auto-Trip Approval Scheme" }], correctOptionId: "o1" },
      { id: "m1_q26", prompt: "Is your visa tied to a specific university?", options: [{ id: "o1", text: "Yes, the sponsor who issued your CAS" }, { id: "o2", text: "No, you can go anywhere" }], correctOptionId: "o1" },
      { id: "m1_q27", prompt: "What should you do if your contact details change?", options: [{ id: "o1", text: "Tell no one" }, { id: "o2", text: "Update the university and UKVI" }, { id: "o3", text: "Post on Instagram" }, { id: "o4", text: "Wait until graduation" }], correctOptionId: "o2" },
      { id: "m1_q28", prompt: "What is the minimum age for a Student Visa?", options: [{ id: "o1", text: "12" }, { id: "o2", text: "16" }, { id: "o3", text: "18" }, { id: "o4", text: "21" }], correctOptionId: "o2" },
      { id: "m1_q29", prompt: "Does a student visa lead to permanent residency automatically?", options: [{ id: "o1", text: "Yes" }, { id: "o2", text: "No" }], correctOptionId: "o2" },
      { id: "m1_q30", prompt: "What is the 'Graduate Route'?", options: [{ id: "o1", text: "A walking path on campus" }, { id: "o2", text: "A post-study work visa for 2-3 years" }, { id: "o3", text: "A bus route to London" }, { id: "o4", text: "A graduation ceremony" }], correctOptionId: "o2" }
    ]
  },
  {
    id: "core_ukvi_m2",
    title: "Module 2: CAS & Financial Compliance",
    timePerQuestionSeconds: 15,
    isRandomized: true,
    isArchived: false,
    isDefault: true,
    category: "core",
    orderIndex: 2,
    questions: [
      { id: "m2_q1", prompt: "What does CAS stand for?", options: [{ id: "o1", text: "Course Admission System" }, { id: "o2", text: "Confirmation of Acceptance for Studies" }, { id: "o3", text: "Certified Academic Statement" }], correctOptionId: "o2" },
      { id: "m2_q2", prompt: "What is a CAS?", options: [{ id: "o1", text: "A visa document" }, { id: "o2", text: "A unique 14-character reference number" }, { id: "o3", text: "A university diploma" }], correctOptionId: "o2" },
      { id: "m2_q3", prompt: "How long is a CAS valid for?", options: [{ id: "o1", text: "3 months" }, { id: "o2", text: "6 months" }, { id: "o3", text: "12 months" }], correctOptionId: "o2" },
      { id: "m2_q4", prompt: "What is the '28-day rule' for financial evidence?", options: [{ id: "o1", text: "Funds must be held for 7 days" }, { id: "o2", text: "Funds must be held for 14 days" }, { id: "o3", text: "Funds must be held for 28 consecutive days" }], correctOptionId: "o3" },
      { id: "m2_q5", prompt: "What is the '31-day rule' for bank statements?", options: [{ id: "o1", text: "Statement must be 1 day old" }, { id: "o2", text: "Statement must be 60 days old" }, { id: "o3", text: "Application must be submitted within 31 days of the statement date" }], correctOptionId: "o3" },
      { id: "m2_q6", prompt: "What happens if your bank balance drops by £1 below the requirement for one day during the 28-day period?", options: [{ id: "o1", text: "Nothing" }, { id: "o2", text: "The 28-day timer resets and the application may fail" }, { id: "o3", text: "You pay a fine" }], correctOptionId: "o2" },
      { id: "m2_q7", prompt: "Whose bank accounts are allowed for visa evidence?", options: [{ id: "o1", text: "Applicant or biological parents/guardians" }, { id: "o2", text: "Friends and siblings" }, { id: "o3", text: "Distant relatives" }], correctOptionId: "o1" },
      { id: "m2_q8", prompt: "Which of the following is UNACCEPTABLE as financial evidence?", options: [{ id: "o1", text: "Savings account" }, { id: "o2", text: "Fixed deposit" }, { id: "o3", text: "Shares, stocks, property, or credit cards" }], correctOptionId: "o3" },
      { id: "m2_q9", prompt: "For how many months of living expenses must you show funds (maximum)?", options: [{ id: "o1", text: "6 months" }, { id: "o2", text: "9 months" }, { id: "o3", text: "12 months" }], correctOptionId: "o2" },
      { id: "m2_q10", prompt: "What is the monthly maintenance requirement for students studying OUTSIDE London?", options: [{ id: "o1", text: "£1,334" }, { id: "o2", text: "£1,023" }, { id: "o3", text: "£900" }], correctOptionId: "o2" },
      { id: "m2_q11", prompt: "What is the monthly maintenance requirement for students studying INSIDE London?", options: [{ id: "o1", text: "£1,023" }, { id: "o2", text: "£1,200" }, { id: "o3", text: "£1,334" }], correctOptionId: "o3" },
      { id: "m2_q12", prompt: "Can paid tuition fees be deducted from the total required funds?", options: [{ id: "o1", text: "No" }, { id: "o2", text: "Yes, they are deducted from the total required" }, { id: "o3", text: "Only if paid in cash" }], correctOptionId: "o2" },
      { id: "m2_q13", prompt: "Can you use a company bank account for your visa application?", options: [{ id: "o1", text: "Yes, always" }, { id: "o2", text: "No, unless it is a sole trader account in your name" }, { id: "o3", text: "Yes, if you are an employee" }], correctOptionId: "o2" },
      { id: "m2_q14", prompt: "What documents are needed if using parent's funds?", options: [{ id: "o1", text: "Birth certificate, consent letter, and bank statement" }, { id: "o2", text: "Only their passport" }, { id: "o3", text: "Only a letter" }], correctOptionId: "o1" },
      { id: "m2_q15", prompt: "What is the earliest you can apply for a student visa from outside the UK?", options: [{ id: "o1", text: "3 months before" }, { id: "o2", text: "6 months before" }, { id: "o3", text: "1 month before" }], correctOptionId: "o2" },
      { id: "m2_q16", prompt: "What is the penalty for a fraudulent statement or document?", options: [{ id: "o1", text: "A warning" }, { id: "o2", text: "Visa refusal and a 10-year ban" }, { id: "o3", text: "A small fine" }], correctOptionId: "o2" },
      { id: "m2_q17", prompt: "How many times can a single CAS be used for a visa application?", options: [{ id: "o1", text: "Once" }, { id: "o2", text: "Twice" }, { id: "o3", text: "Unlimited" }], correctOptionId: "o1" },
      { id: "m2_q18", prompt: "What should you do if there is a passport error on your CAS?", options: [{ id: "o1", text: "Apply anyway" }, { id: "o2", text: "Contact the university to update the CAS via SMS" }, { id: "o3", text: "Manually edit the CAS" }], correctOptionId: "o2" },
      { id: "m2_q19", prompt: "Can a fixed deposit account be used?", options: [{ id: "o1", text: "No" }, { id: "o2", text: "Yes, if funds are withdrawable at any time" }, { id: "o3", text: "Only if it's for 5 years" }], correctOptionId: "o2" },
      { id: "m2_q20", prompt: "What is required to use an education loan as evidence?", options: [{ id: "o1", text: "An email from the bank" }, { id: "o2", text: "An official loan sanction letter" }, { id: "o3", text: "A verbal promise" }], correctOptionId: "o2" },
      { id: "m2_q21", prompt: "Can you use evidence of private accommodation payments to reduce the maintenance requirement?", options: [{ id: "o1", text: "Yes" }, { id: "o2", text: "No" }, { id: "o3", text: "Only if paid to a relative" }], correctOptionId: "o2" },
      { id: "m2_q22", prompt: "What exchange rate does UKVI use for currency conversion?", options: [{ id: "o1", text: "Google Finance" }, { id: "o2", text: "OANDA rate on the date of submission" }, { id: "o3", text: "XE.com" }], correctOptionId: "o2" },
      { id: "m2_q23", prompt: "What does RQF stand for?", options: [{ id: "o1", text: "Research Quality Foundation" }, { id: "o2", text: "Regulated Qualifications Framework" }, { id: "o3", text: "Regional Quality Forum" }], correctOptionId: "o2" },
      { id: "m2_q24", prompt: "What RQF level is a Master's degree?", options: [{ id: "o1", text: "Level 5" }, { id: "o2", text: "Level 6" }, { id: "o3", text: "Level 7" }], correctOptionId: "o3" },
      { id: "m2_q25", prompt: "What RQF level is a Bachelor's degree?", options: [{ id: "o1", text: "Level 4" }, { id: "o2", text: "Level 6" }, { id: "o3", text: "Level 7" }], correctOptionId: "o2" },
      { id: "m2_q26", prompt: "Can you re-use a CAS if your visa was refused and you want to re-apply?", options: [{ id: "o1", text: "Yes" }, { id: "o2", text: "No, a new CAS is needed" }, { id: "o3", text: "Only if the refusal was a mistake" }], correctOptionId: "o2" },
      { id: "m2_q27", prompt: "Which entity issues the CAS?", options: [{ id: "o1", text: "Home Office via University SMS (Sponsorship Management System)" }, { id: "o2", text: "The British Embassy" }, { id: "o3", text: "The local police" }], correctOptionId: "o1" },
      { id: "m2_q28", prompt: "What details must a bank statement include?", options: [{ id: "o1", text: "Name, Account #, Dates, and Balance" }, { id: "o2", text: "Only the balance" }, { id: "o3", text: "Only the bank's logo" }], correctOptionId: "o1" },
      { id: "m2_q29", prompt: "How do you prove government sponsorship?", options: [{ id: "o1", text: "A screenshot" }, { id: "o2", text: "An official financial sponsorship letter" }, { id: "o3", text: "A personal letter" }], correctOptionId: "o2" },
      { id: "m2_q30", prompt: "What is the purpose of the university deposit?", options: [{ id: "o1", text: "It is a processing fee" }, { id: "o2", text: "It shows commitment and reduces the remaining tuition balance on the CAS" }, { id: "o3", text: "It is for health insurance" }], correctOptionId: "o2" }
    ]
  },
  {
    id: "core_ukvi_m3",
    title: "Module 3: Academic, University & Course Knowledge",
    timePerQuestionSeconds: 15,
    isRandomized: true,
    isArchived: false,
    isDefault: true,
    category: "core",
    orderIndex: 3,
    questions: [
      { id: "m3_q1", prompt: "When asked 'Why this course?', what should you emphasize?", options: [{ id: "o1", text: "The location" }, { id: "o2", text: "The weather" }, { id: "o3", text: "Specific modules and career alignment" }], correctOptionId: "o3" },
      { id: "m3_q2", prompt: "How many credits are typically required for a Master's degree in the UK?", options: [{ id: "o1", text: "120" }, { id: "o2", text: "150" }, { id: "o3", text: "180" }], correctOptionId: "o3" },
      { id: "m3_q3", prompt: "How many credits are typically required for a 3-year Bachelor's degree in the UK?", options: [{ id: "o1", text: "180" }, { id: "o2", text: "240" }, { id: "o3", text: "300" }, { id: "o4", text: "360" }], correctOptionId: "o4" },
      { id: "m3_q4", prompt: "What are common assessment methods in UK higher education?", options: [{ id: "o1", text: "Attendance only" }, { id: "o2", text: "Coursework, exams, presentations, and dissertation" }, { id: "o3", text: "Physical fitness tests" }], correctOptionId: "o2" },
      { id: "m3_q5", prompt: "When comparing universities, what should you look at?", options: [{ id: "o1", text: "The colors of the logo" }, { id: "o2", text: "Modules, tuition, facilities, and industry links" }, { id: "o3", text: "Proximity to shopping malls" }], correctOptionId: "o2" },
      { id: "m3_q6", prompt: "What does RQF Level 7 represent?", options: [{ id: "o1", text: "Foundation" }, { id: "o2", text: "Bachelor's" }, { id: "o3", text: "Master's Degree" }], correctOptionId: "o3" },
      { id: "m3_q7", prompt: "What does RQF Level 6 represent?", options: [{ id: "o1", text: "Foundation" }, { id: "o2", text: "Bachelor's Degree" }, { id: "o3", text: "Master's" }], correctOptionId: "o2" },
      { id: "m3_q8", prompt: "How should you justify switching fields of study?", options: [{ id: "o1", text: "'I was bored'" }, { id: "o2", text: "Highlight transferable skills and new career goals" }, { id: "o3", text: "'My parents told me to'" }], correctOptionId: "o2" },
      { id: "m3_q9", prompt: "What does 'vague knowledge' of your course suggest to an interviewer?", options: [{ id: "o1", text: "Lack of genuine interest or research" }, { id: "o2", text: "High intelligence" }, { id: "o3", text: "Modesty" }], correctOptionId: "o1" },
      { id: "m3_q10", prompt: "What is a dissertation in the context of a UK degree?", options: [{ id: "o1", text: "A small quiz" }, { id: "o2", text: "An independent research project" }, { id: "o3", text: "A group presentation" }], correctOptionId: "o2" },
      { id: "m3_q11", prompt: "Why is the location of the university important to know?", options: [{ id: "o1", text: "To find the best pubs" }, { id: "o2", text: "To understand the city, campus environment, and distance from hubs" }, { id: "o3", text: "To plan weekend trips" }], correctOptionId: "o2" },
      { id: "m3_q12", prompt: "Why choose the UK over your home country for education?", options: [{ id: "o1", text: "Interactive learning and an international environment" }, { id: "o2", text: "It's easier to pass" }, { id: "o3", text: "To get a job immediately" }], correctOptionId: "o1" },
      { id: "m3_q13", prompt: "How can you show you are prepared for your course?", options: [{ id: "o1", text: "By naming 3-4 specific modules you will study" }, { id: "o2", text: "By showing your new suitcase" }, { id: "o3", text: "By knowing the university's founding year" }], correctOptionId: "o1" },
      { id: "m3_q14", prompt: "What is the typical duration of a full-time Master's degree in the UK?", options: [{ id: "o1", text: "6 months" }, { id: "o2", text: "1 year" }, { id: "o3", text: "2 years" }], correctOptionId: "o2" },
      { id: "m3_q15", prompt: "Why is the 1-year duration of a UK Master's often appealing?", options: [{ id: "o1", text: "It's less work" }, { id: "o2", text: "It saves time and overall living costs" }, { id: "o3", text: "You graduate faster to start a business in the UK" }], correctOptionId: "o2" },
      { id: "m3_q16", prompt: "What does ATAS stand for?", options: [{ id: "o1", text: "Advanced Travel Authorization System" }, { id: "o2", text: "Academic Technology Approval Scheme" }, { id: "o3", text: "Automated Tracking and Safety" }], correctOptionId: "o2" },
      { id: "m3_q17", prompt: "What facilities should you be able to discuss?", options: [{ id: "o1", text: "Local restaurants" }, { id: "o2", text: "Labs, libraries, and specialized software" }, { id: "o3", text: "Gyms only" }], correctOptionId: "o2" },
      { id: "m3_q18", prompt: "What is 'Academic Progression'?", options: [{ id: "o1", text: "Advancing in learning depth and level" }, { id: "o2", text: "Passing all exams" }, { id: "o3", text: "Staying at the same level for 5 years" }], correctOptionId: "o1" },
      { id: "m3_q19", prompt: "Why might studying for the same degree twice be a problem?", options: [{ id: "o1", text: "It's too expensive" }, { id: "o2", text: "It is suspicious and lacks academic progression" }, { id: "o3", text: "The university won't allow it" }], correctOptionId: "o2" },
      { id: "m3_q20", prompt: "What are typical teaching methods in the UK?", options: [{ id: "o1", text: "Lectures, seminars, workshops, and tutorials" }, { id: "o2", text: "Watching videos only" }, { id: "o3", text: "Self-study with no guidance" }], correctOptionId: "o1" },
      { id: "m3_q21", prompt: "Why should you research key professors in your department?", options: [{ id: "o1", text: "To get their autographs" }, { id: "o2", text: "It shows research strength and alignment with your interests" }, { id: "o3", text: "To know who to avoid" }], correctOptionId: "o2" },
      { id: "m3_q22", prompt: "What is 'blended learning'?", options: [{ id: "o1", text: "Learning multiple languages" }, { id: "o2", text: "A mix of classroom-based and online learning" }, { id: "o3", text: "Mixing different subjects" }], correctOptionId: "o2" },
      { id: "m3_q23", prompt: "How should you use university rankings in an interview?", options: [{ id: "o1", text: "Quote specific QS or THE (Times Higher Education) numbers" }, { id: "o2", text: "Say 'It's the best'" }, { id: "o3", text: "Ignore them" }], correctOptionId: "o1" },
      { id: "m3_q24", prompt: "What is the difference between Core and Elective modules?", options: [{ id: "o1", text: "Compulsory vs. Optional" }, { id: "o2", text: "Hard vs. Easy" }, { id: "o3", text: "Morning vs. Evening" }], correctOptionId: "o1" },
      { id: "m3_q25", prompt: "Which document confirms your eligibility for the course and visa?", options: [{ id: "o1", text: "High school diploma" }, { id: "o2", text: "CAS" }, { id: "o3", text: "Bank statement" }], correctOptionId: "o2" },
      { id: "m3_q26", prompt: "Why might a student choose a university outside London?", options: [{ id: "o1", text: "Lower cost of living and specific environment" }, { id: "o2", text: "London is boring" }, { id: "o3", text: "There are no universities in London" }], correctOptionId: "o1" },
      { id: "m3_q27", prompt: "What is the primary goal of a dissertation?", options: [{ id: "o1", text: "To write a lot of pages" }, { id: "o2", text: "To apply research methodology to a specific problem" }, { id: "o3", text: "To work in a team" }], correctOptionId: "o2" },
      { id: "m3_q28", prompt: "What is the risk of forgetting your exact degree name during an interview?", options: [{ id: "o1", text: "None" }, { id: "o2", text: "High risk of visa refusal due to lack of credibility" }, { id: "o3", text: "You might get a different degree" }], correctOptionId: "o2" },
      { id: "m3_q29", prompt: "What is a 'pre-sessional' course?", options: [{ id: "o1", text: "A course for English language preparation before the main course" }, { id: "o2", text: "A course taken after graduation" }, { id: "o3", text: "A hobby class" }], correctOptionId: "o1" },
      { id: "m3_q30", prompt: "Why is looking at student support services important?", options: [{ id: "o1", text: "It shows realistic preparation for life abroad" }, { id: "o2", text: "To get free stuff" }, { id: "o3", text: "To find a part-time job" }], correctOptionId: "o1" }
    ]
  },
  {
    id: "core_ukvi_m4",
    title: "Module 4: Career Progression & Financial Justification",
    timePerQuestionSeconds: 15,
    isRandomized: true,
    isArchived: false,
    isDefault: true,
    category: "core",
    orderIndex: 4,
    questions: [
      { id: "m4_q1", prompt: "What should your career plans focus on?", options: [{ id: "o1", text: "Finding any job in the UK" }, { id: "o2", text: "Returning home for a specific role or company" }, { id: "o3", text: "Becoming a digital nomad" }], correctOptionId: "o2" },
      { id: "m4_q2", prompt: "What does ROI (Return on Investment) mean for your studies?", options: [{ id: "o1", text: "It makes logical financial sense for your career growth" }, { id: "o2", text: "The name of a scholarship" }, { id: "o3", text: "A type of tax" }], correctOptionId: "o1" },
      { id: "m4_q3", prompt: "What is the work limit for student visa holders during term time?", options: [{ id: "o1", text: "10 hours/week" }, { id: "o2", text: "20 hours/week" }, { id: "o3", text: "40 hours/week" }], correctOptionId: "o2" },
      { id: "m4_q4", prompt: "Should you rely on part-time work to cover your tuition or living costs?", options: [{ id: "o1", text: "Yes, it's expected" }, { id: "o2", text: "No, you must have the funds already" }, { id: "o3", text: "Only if you get a high-paying job" }], correctOptionId: "o2" },
      { id: "m4_q5", prompt: "Which of these is FORBIDDEN work for a student visa holder?", options: [{ id: "o1", text: "Working in a cafe" }, { id: "o2", text: "Self-employment, business, or professional sports" }, { id: "o3", text: "Tutoring" }], correctOptionId: "o2" },
      { id: "m4_q6", prompt: "What should you know about your parent's sponsorship?", options: [{ id: "o1", text: "Only their name" }, { id: "o2", text: "Their profession, income source, and commitment to your education" }, { id: "o3", text: "Nothing" }], correctOptionId: "o2" },
      { id: "m4_q7", prompt: "Why is it important to show you don't intend to stay permanently?", options: [{ id: "o1", text: "To show strong ties to your home country" }, { id: "o2", text: "Because the UK is too crowded" }, { id: "o3", text: "To get a cheaper visa" }], correctOptionId: "o1" },
      { id: "m4_q8", prompt: "What is the work limit during official university breaks?", options: [{ id: "o1", text: "20 hours/week" }, { id: "o2", text: "30 hours/week" }, { id: "o3", text: "Full-time" }], correctOptionId: "o3" },
      { id: "m4_q9", prompt: "What happens if you tell an officer you'll use part-time work to pay tuition?", options: [{ id: "o1", text: "You get a work permit" }, { id: "o2", text: "Visa refusal" }, { id: "o3", text: "They give you a loan" }], correctOptionId: "o2" },
      { id: "m4_q10", prompt: "What is the 'Graduate Route'?", options: [{ id: "o1", text: "A 1-year visa" }, { id: "o2", text: "A 2-year post-study work visa (3 years for PhD)" }, { id: "o3", text: "A permanent residency path" }], correctOptionId: "o2" },
      { id: "m4_q11", prompt: "Why show ties to home if you plan to use the Graduate Route (PSW)?", options: [{ id: "o1", text: "Because the PSW is a temporary route, not permanent settlement" }, { id: "o2", text: "To get a discount on the IHS" }, { id: "o3", text: "It is not necessary" }], correctOptionId: "o1" },
      { id: "m4_q12", prompt: "What constitutes an 'economic tie' to your home country?", options: [{ id: "o1", text: "Property, job offers, or a family business" }, { id: "o2", text: "Having a bank account" }, { id: "o3", text: "Knowing the president" }], correctOptionId: "o1" },
      { id: "m4_q13", prompt: "How should your sponsor's income be presented?", options: [{ id: "o1", text: "Accurate and verifiable via documents" }, { id: "o2", text: "As a rough estimate" }, { id: "o3", text: "As 'a lot of money'" }], correctOptionId: "o1" },
      { id: "m4_q14", prompt: "What should you consider in your 'total cost' calculation?", options: [{ id: "o1", text: "Tuition, living expenses, and travel" }, { id: "o2", text: "Only tuition" }, { id: "o3", text: "Only living expenses" }], correctOptionId: "o1" },
      { id: "m4_q15", prompt: "What does IHS stand for?", options: [{ id: "o1", text: "International Home Security" }, { id: "o2", text: "Immigration Health Surcharge" }, { id: "o3", text: "Institute for Higher Studies" }], correctOptionId: "o2" },
      { id: "m4_q16", prompt: "What is the purpose of the IHS?", options: [{ id: "o1", text: "To pay for university labs" }, { id: "o2", text: "To access the National Health Service (NHS)" }, { id: "o3", text: "To buy a BRP" }], correctOptionId: "o2" },
      { id: "m4_q17", prompt: "How does a job offer in your home country help your application?", options: [{ id: "o1", text: "It serves as proof of intent to return" }, { id: "o2", text: "It gives you extra money now" }, { id: "o3", text: "It makes you look busy" }], correctOptionId: "o1" },
      { id: "m4_q18", prompt: "What is a risk of having a sponsor with very low income?", options: [{ id: "o1", text: "They might be considered non-credible for funding your studies" }, { id: "o2", text: "None, as long as the money is in the bank" }, { id: "o3", text: "You get a scholarship" }], correctOptionId: "o1" },
      { id: "m4_q19", prompt: "What is a potential implication of having close relatives settled in the UK?", options: [{ id: "o1", text: "It implies a potential intent for permanent settlement" }, { id: "o2", text: "It means you will have free accommodation" }, { id: "o3", text: "It has no impact" }], correctOptionId: "o1" },
      { id: "m4_q20", prompt: "What is a realistic accommodation cost to estimate for a student?", options: [{ id: "o1", text: "A realistic estimate based on the city (e.g., £500-£800/month)" }, { id: "o2", text: "£50/month" }, { id: "o3", text: "£5000/month" }], correctOptionId: "o1" },
      { id: "m4_q21", prompt: "Is it appropriate to say you want to settle permanently in the UK during a student visa interview?", options: [{ id: "o1", text: "No, it is a temporary route" }, { id: "o2", text: "Yes, it shows ambition" }, { id: "o3", text: "Only if you are rich" }], correctOptionId: "o1" },
      { id: "m4_q22", prompt: "What should you base your salary expectations on?", options: [{ id: "o1", text: "Industry averages in your home country/global market" }, { id: "o2", text: "Just a high number" }, { id: "o3", text: "'Whatever I get'" }], correctOptionId: "o1" },
      { id: "m4_q23", prompt: "What does 'non-genuine sponsor' mean?", options: [{ id: "o1", text: "Fund parking (money temporarily placed in an account)" }, { id: "o2", text: "Someone who is not a relative" }, { id: "o3", text: "A sponsor who is retired" }], correctOptionId: "o1" },
      { id: "m4_q24", prompt: "Can you work full-time in the UK before you have officially graduated?", options: [{ id: "o1", text: "Yes" }, { id: "o2", text: "No, it is generally illegal to work full-time during term" }, { id: "o3", text: "Only on weekends" }], correctOptionId: "o2" },
      { id: "m4_q25", prompt: "What is 'fund parking'?", options: [{ id: "o1", text: "Temporary deposits to pass the financial check without having the money available for study" }, { id: "o2", text: "Parking a car at the bank" }, { id: "o3", text: "Saving for a rainy day" }], correctOptionId: "o1" },
      { id: "m4_q26", prompt: "How do you prove business profits for a sponsor?", options: [{ id: "o1", text: "Business registration, tax returns, and profit history" }, { id: "o2", text: "A simple letter" }, { id: "o3", text: "A photo of the office" }], correctOptionId: "o1" },
      { id: "m4_q27", prompt: "Why does UKVI ask about your current employment status?", options: [{ id: "o1", text: "To assess financial standing and career continuity" }, { id: "o2", text: "To see if you are lazy" }, { id: "o3", text: "To tax your current income" }], correctOptionId: "o1" },
      { id: "m4_q28", prompt: "What is the problem with 'generic answers' in an interview?", options: [{ id: "o1", text: "They lack substance and don't prove you are a genuine student" }, { id: "o2", text: "They are too long" }, { id: "o3", text: "They are too professional" }], correctOptionId: "o1" },
      { id: "m4_q29", prompt: "Who is responsible for repaying an education loan?", options: [{ id: "o1", text: "The university" }, { id: "o2", text: "The student or their sponsor" }, { id: "o3", text: "The UK government" }], correctOptionId: "o2" },
      { id: "m4_q30", prompt: "How can a startup plan benefit your application?", options: [{ id: "o1", text: "By showing how specific modules help build your enterprise" }, { id: "o2", text: "By showing you are rich" }, { id: "o3", text: "It doesn't help" }], correctOptionId: "o1" }
    ]
  },
  {
    id: "core_ukvi_m5",
    title: "Module 5: Interview Delivery & Behavioral Excellence",
    timePerQuestionSeconds: 15,
    isRandomized: true,
    isArchived: false,
    isDefault: true,
    category: "core",
    orderIndex: 5,
    questions: [
      { id: "m5_q1", prompt: "What is a common technical mistake during a video interview?", options: [{ id: "o1", text: "Looking at the camera" }, { id: "o2", text: "Reading off notes or a script" }, { id: "o3", text: "Speaking too clearly" }], correctOptionId: "o2" },
      { id: "m5_q2", prompt: "What should you do if the audio freezes during a video interview?", options: [{ id: "o1", text: "Disconnect immediately" }, { id: "o2", text: "Stay calm and politely ask the interviewer to repeat" }, { id: "o3", text: "Shout at the screen" }], correctOptionId: "o2" },
      { id: "m5_q3", prompt: "Why are 'scripted answers' problematic?", options: [{ id: "o1", text: "They sound unnatural and can obscure your true intent" }, { id: "o2", text: "They are too perfect" }, { id: "o3", text: "They save time" }], correctOptionId: "o1" },
      { id: "m5_q4", prompt: "What is the ideal environment for your visa interview?", options: [{ id: "o1", text: "A busy cafe" }, { id: "o2", text: "A quiet, private room with stable internet" }, { id: "o3", text: "A park" }], correctOptionId: "o2" },
      { id: "m5_q5", prompt: "How should you react if you don't know a specific detail asked by the interviewer?", options: [{ id: "o1", text: "Make something up" }, { id: "o2", text: "Give a calm, honest response and explain what you do know" }, { id: "o3", text: "Cry" }], correctOptionId: "o2" },
      { id: "m5_q6", prompt: "What might an interviewer suspect if you keep looking to the side?", options: [{ id: "o1", text: "You have an eye problem" }, { id: "o2", text: "You are being prompted or cheating" }, { id: "o3", text: "You are shy" }], correctOptionId: "o2" },
      { id: "m5_q7", prompt: "What is the best tone to use during the interview?", options: [{ id: "o1", text: "Aggressive" }, { id: "o2", text: "Whispering" }, { id: "o3", text: "Professional, confident, and natural" }], correctOptionId: "o3" },
      { id: "m5_q8", prompt: "What is the impact of a discrepancy between your interview and your application forms?", options: [{ id: "o1", text: "None" }, { id: "o2", text: "It casts doubt on your credibility" }, { id: "o3", text: "It's expected" }], correctOptionId: "o2" },
      { id: "m5_q9", prompt: "What is the recommended attire for the interview?", options: [{ id: "o1", text: "Pajamas" }, { id: "o2", text: "Professional or smart-casual" }, { id: "o3", text: "A tuxedo" }], correctOptionId: "o2" },
      { id: "m5_q10", prompt: "Why is punctuality important for a virtual interview?", options: [{ id: "o1", text: "To test your setup and show respect" }, { id: "o2", text: "It's not, you can join anytime" }, { id: "o3", text: "To get a better seat" }], correctOptionId: "o1" },
      { id: "m5_q11", prompt: "How should you answer 'Who filled in your application form?'?", options: [{ id: "o1", text: "'An agent did everything'" }, { id: "o2", text: "'I did it myself / I reviewed and confirmed everything'" }, { id: "o3", text: "'I don't know'" }], correctOptionId: "o2" },
      { id: "m5_q12", prompt: "What do frequent long hesitations or silences suggest?", options: [{ id: "o1", text: "You are thinking deeply" }, { id: "o2", text: "Poor English proficiency or being unprepared" }, { id: "o3", text: "You are bored" }], correctOptionId: "o2" },
      { id: "m5_q13", prompt: "How should you handle a challenging follow-up question?", options: [{ id: "o1", text: "Get defensive" }, { id: "o2", text: "Defend your position logically and calmly" }, { id: "o3", text: "Change the subject" }], correctOptionId: "o2" },
      { id: "m5_q14", prompt: "What if the interviewer cuts your answer short?", options: [{ id: "o1", text: "Stay calm and wait for the next question" }, { id: "o2", text: "Keep talking anyway" }, { id: "o3", text: "Get angry" }], correctOptionId: "o1" },
      { id: "m5_q15", prompt: "What happens if you are caught reading from a PDF during the interview?", options: [{ id: "o1", text: "High chance of visa refusal" }, { id: "o2", text: "You get a warning" }, { id: "o3", text: "Nothing" }], correctOptionId: "o1" },
      { id: "m5_q16", prompt: "Which body language should you avoid?", options: [{ id: "o1", text: "Smiling" }, { id: "o2", text: "Slouching, fidgeting, or avoiding eye contact" }, { id: "o3", text: "Nodding" }], correctOptionId: "o2" },
      { id: "m5_q17", prompt: "How should you address a past visa refusal?", options: [{ id: "o1", text: "Hide it" }, { id: "o2", text: "Be honest and explain the reason and how you've addressed it" }, { id: "o3", text: "Blame the embassy" }], correctOptionId: "o2" },
      { id: "m5_q18", prompt: "What is the consequence of hiding a previous visa refusal?", options: [{ id: "o1", text: "Mandatory refusal for deception" }, { id: "o2", text: "A small delay" }, { id: "o3", text: "Nothing" }], correctOptionId: "o1" },
      { id: "m5_q19", prompt: "Where should your phone be during the interview?", options: [{ id: "o1", text: "In your hand" }, { id: "o2", text: "Silent and out of sight" }, { id: "o3", text: "On the table" }], correctOptionId: "o2" },
      { id: "m5_q20", prompt: "What is a better approach than a simple 'Yes/No' answer?", options: [{ id: "o1", text: "A 'Yes/No' followed by brief context and explanation" }, { id: "o2", text: "Just 'Yes'" }, { id: "o3", text: "A 10-minute story" }], correctOptionId: "o1" },
      { id: "m5_q21", prompt: "Why is good lighting important for a video interview?", options: [{ id: "o1", text: "For visibility and identity verification" }, { id: "o2", text: "To look like a movie star" }, { id: "o3", text: "It doesn't matter" }], correctOptionId: "o1" },
      { id: "m5_q22", prompt: "Should you argue with the interviewer if they challenge your answers?", options: [{ id: "o1", text: "Yes, stand your ground" }, { id: "o2", text: "No, it is unprofessional; remain respectful" }, { id: "o3", text: "Walk away" }], correctOptionId: "o2" },
      { id: "m5_q23", prompt: "What is 'active listening' in an interview?", options: [{ id: "o1", text: "Hearing but not responding" }, { id: "o2", text: "Processing the question and responding directly to it" }, { id: "o3", text: "Looking around the room" }], correctOptionId: "o2" },
      { id: "m5_q24", prompt: "Who should be in the room with you during the interview?", options: [{ id: "o1", text: "You should be entirely alone" }, { id: "o2", text: "Your parents" }, { id: "o3", text: "Your agent" }], correctOptionId: "o1" },
      { id: "m5_q25", prompt: "Why might an interviewer cross-examine your answers?", options: [{ id: "o1", text: "To verify the authenticity and consistency of your claims" }, { id: "o2", text: "To be mean" }, { id: "o3", text: "To pass time" }], correctOptionId: "o1" },
      { id: "m5_q26", prompt: "Should you use memory cues or scripts?", options: [{ id: "o1", text: "No, rely on your understanding of your own application" }, { id: "o2", text: "Yes, write them on the wall" }, { id: "o3", text: "Use a teleprompter" }], correctOptionId: "o1" },
      { id: "m5_q27", prompt: "What should you do at the end of the interview?", options: [{ id: "o1", text: "Close the laptop immediately" }, { id: "o2", text: "Thank the interviewer for their time" }, { id: "o3", text: "Ask for their phone number" }], correctOptionId: "o2" },
      { id: "m5_q28", prompt: "What does it mean if you give different answers to the same question asked twice?", options: [{ id: "o1", text: "It is a major red flag for credibility" }, { id: "o2", text: "You are creative" }, { id: "o3", text: "You forgot the first answer" }], correctOptionId: "o1" },
      { id: "m5_q29", prompt: "What is a best practice for interview preparation?", options: [{ id: "o1", text: "Conducting mock interviews with peers or mentors" }, { id: "o2", text: "Doing nothing" }, { id: "o3", text: "Just reading the university website once" }], correctOptionId: "o1" },
      { id: "m5_q30", prompt: "What gives you the highest chance of passing the credibility test?", options: [{ id: "o1", text: "Genuine enthusiasm and thorough research" }, { id: "o2", text: "Being lucky" }, { id: "o3", text: "Having a lot of money" }], correctOptionId: "o1" }
    ]
  }
];

export const CORE_UKVI_MOCK_SET = {
  id: "core_mock_default",
  title: "Official UKVI Mock Interview (Core)",
  timePerQuestionSeconds: 60,
  isRandomized: true,
  isDefault: true,
  category: "core",
  questions: [
    "Why did you choose the UK over other countries like USA, Canada or Australia?",
    "Why this specific university and why not a similar course in your home country?",
    "Can you explain your study gap if any, and what did you do during that time?",
    "How will this course help your career plans in your home country?",
    "Who is sponsoring your studies and what is their occupation/annual income?",
    "What are your plans after completing your course in the UK?",
    "Where will you be staying in the UK and how far is it from the campus?",
    "What are the modules you will be studying in this course?"
  ]
};
