import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebaseAdmin';

export async function POST(req: Request) {
  try {
    const modulesRef = adminDb.collection('learning_modules');

    const seedModules = [
      {
        id: "module_1",
        order: 1,
        title: "Module 1: Fundamentals of University & UKVI Credibility Interviews",
        summary: "Core topics: Purpose of interviews, Home Office guidelines, university vs. UKVI expectations, genuine student status (GTE/Genuine Student Test).",
        learningResources: [
          {
            heading: "1. Purpose of the Credibility Interview",
            content: "• The 'Genuine Student' Rule: UK Visas and Immigration (UKVI) and UK universities conduct credibility interviews to verify that an applicant's primary purpose for coming to the UK is academic study, not illegal work or permanent settlement.\n• Entry Clearance Officer (ECO) Role: The ECO assesses whether the candidate possesses sufficient English proficiency, genuine academic intent, and realistic financial backing.\n• University Pre-CAS Interviews: Before issuing a Confirmation of Acceptance for Studies (CAS), universities conduct internal credibility interviews to safeguard their UKVI Student Sponsor License."
          },
          {
            heading: "2. Institutional Framework",
            content: "• Pre-CAS Interview (University): Conducted by admissions or compliance teams. Focuses on academic background, suitability for the course, and basic financial capability.\n• UKVI Credibility Interview (Home Office): Conducted online or via phone. Focuses on detailed verification of financial sources, course details, and long-term career logic."
          },
          {
            heading: "3. Key Assessment Indicators",
            content: "• Academic Fit & Progression: Explaining why this specific degree is a logical next step.\n• Language Proficiency: Candidates must converse fluently without relying on interpreters or scripts.\n• Relevance of Choice: Ability to explain why the applicant chose the UK over their home country or alternative destinations."
          }
        ],
        questionPool: [
          {
            id: "m1_q1",
            question: "What is the primary objective of a UKVI Credibility Interview?",
            options: [
              "To assess if the student qualifies for permanent residency",
              "To confirm the applicant is a genuine student with authentic intentions to study",
              "To test the student's ability to work full-time in the UK",
              "To evaluate the student's fitness levels for entry"
            ],
            answerIndex: 1
          },
          {
            id: "m1_q2",
            question: "Who conducts the Pre-CAS interview?",
            options: [
              "Home Office Entry Clearance Officer",
              "The university's admissions or compliance team",
              "The local embassy security team",
              "The British High Commissioner"
            ],
            answerIndex: 1
          }
          // Q3 to Q30 would go here...
        ],
        isDefault: true,
        passScore: 80,
        createdAt: new Date(),
      },
      {
        id: "module_2",
        order: 2,
        title: "Module 2: CAS & Financial Compliance",
        summary: "Core topics: What CAS is, issuance rules, strict 28-day financial rules, acceptable fund sources, tuition deposits, dependent/living expense calculations.",
        learningResources: [
          {
            heading: "1. Understanding the CAS",
            content: "• Definition: A unique 14-character alphanumeric reference number generated by a licensed UK university via SMS.\n• Validity: Valid for 6 months from the date of issue and can only be used once for a visa application."
          },
          {
            heading: "2. UKVI Financial Requirements & Rules",
            content: "• Required Funds: Tuition balance + Living Expenses (£1,334/mo Inner London, £1,023/mo Outer London up to 9 months).\n• 28-Day Rule: Total required money must remain in the account continuously for 28 consecutive days without dropping below the minimum.\n• 31-Day Rule: Statement closing date must be within 31 days of visa submission."
          }
        ],
        questionPool: [
          // Module 2 Questions...
        ],
        isDefault: true,
        passScore: 80,
        createdAt: new Date(),
      },
      {
        id: "module_3",
        order: 3,
        title: "Module 3: Academic, University & Course Knowledge Assessment",
        summary: "Core topics: Articulating course structure, modules, RQF levels, assessment methods, university location/facilities, comparison with home country & other UK institutions.",
        learningResources: [
          {
            heading: "1. In-Depth Course Knowledge",
            content: "• Module Awareness: Articulate core and elective modules by exact title.\n• Credits: UK Master's = 180 credits; Bachelor's = 360 credits over 3 years."
          }
        ],
        questionPool: [
          // Module 3 Questions...
        ],
        isDefault: true,
        passScore: 80,
        createdAt: new Date(),
      },
      {
        id: "module_4",
        order: 4,
        title: "Module 4: Career Progression, Return Intentions & Financial Justification",
        summary: "Core topics: Post-study career path, ROI, tying qualifications to home-country job markets, avoiding immigration/work-intent red flags.",
        learningResources: [
          {
            heading: "1. Articulating Career Strategy",
            content: "• Target Roles & Employers: Name specific job titles and home country companies.\n• Work Limits: 20 hours/week max during term time. Income cannot be relied upon to pay tuition."
          }
        ],
        questionPool: [
          // Module 4 Questions...
        ],
        isDefault: true,
        passScore: 80,
        createdAt: new Date(),
      },
      {
        id: "module_5",
        order: 5,
        title: "Module 5: Interview Delivery, Common Failure Reasons & Behavioral Excellence",
        summary: "Core topics: Top refusal triggers, communication standards, body language, tone, avoiding memorized answers, managing technical/logistical issues.",
        learningResources: [
          {
            heading: "1. Avoid Common Failure Triggers",
            content: "• Never read off hidden notes/screens off-camera.\n• Avoid generic/scripted responses; answer spontaneously and naturally."
          }
        ],
        questionPool: [
          // Module 5 Questions...
        ],
        isDefault: true,
        passScore: 80,
        createdAt: new Date(),
      }
    ];

    const batch = adminDb.batch();

    seedModules.forEach((mod) => {
      const docRef = modulesRef.doc(mod.id);
      batch.set(docRef, mod, { merge: true });
    });

    await batch.commit();

    return NextResponse.json({ message: "Successfully seeded full learning modules!" }, { status: 200 });
  } catch (error: any) {
    console.error("Seeding error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
